pdf:
	rm -rf pyschool-poster.pdf
	quarto render pyschool-poster.qmd
	open pyschool-poster.pdf

html:
	rm -rf pyschool-poster.html
	quarto render pyschool-poster.qmd
	open pyschool-poster.html

test:
	quarto render template.qmd
	open template.html